debug: false
logging:
  #file:
    #name: app.log
  level:
    root: info
    org.apache.kafka: error
    org.springframework.kafka.config: debug
server: 
  port: 9000
spring:
  application:
    name: inventory-processor
  cloud:    stream:
      function:        definition: processItem, sinkInventory
      bindings:
        processItem-in-0:
          destination: items
          consumer:            use-native-decoding: true
        processItem-out-0:
          destination: inventory
          producer:            use-native-encoding: true
        sinkInventory-in-0:
          destination: inventory
          consumer:
            use-native-decoding: true
      kafka:
        streams:
          binder:
            functions:
              sinkInventory:
                application-id: ${spring.application.name}-reader
              processItem:
                application-id: ${spring.application.name}-item
            applicationId: ${spring.application.name}-stream
            brokers:
            - localhost:19093
            - localhost:19094
            configuration:
              schema.registry.url: http://localhost:8081              
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
              inventory-materialized-as: inventory-table
              processing.guarantee: exactly_once
            autoCreateTopics: false
            autoAddPartitions: false
          bindings:
            processItem-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            processItem-in-0.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            processItem-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            processItem-out-0.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            sinkInventory-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            sinkInventory-in-0.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde