debug: true
logging:
  file:    name: app.log
  level:    root: info
    org.apache.kafka.streams: info
server: 
  port: 9000
spring:
  cloud:    stream:
      function:        definition: sinkItem, sinkInventory, processItem
      bindings:
        sinkItem-in-0:
          destination: items
          group: item-readers
        sinkInventory-in-0:
          destination: inventory
          group: inventory-readers
        processItem-in-0:
          destination: items
        processItem-out-0:
          destination: inventory
      kafka:
        streams:
          binder:
            brokers:
            - localhost:19093
            - localhost:19094
            configuration:
              schema.registry.url: http://localhost:8081
              default:
                key.serde: io.confluent.kafka.streams.serdes.avro.PrimitiveAvroSerde
                value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            auto-create-topics: false
            autoAddPartitions: false