debug: false
logging:
  #file:
    #name: app.log
  level:
    root: info
    org.apache.kafka: error
    org.springframework.kafka.config: debug
server:
  port: 9001
spring:
  cloud:
    stream:
      function:        definition: output
      kafka:
        binder:
          auto-create-topics: false
          autoAddPartitions: false
          brokers:
          - localhost:19093
          - localhost:19094   
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.LongSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
      bindings:
        output-out-0:
          destination: items
          content-type: application/*+avro
          producer:            useNativeEncoding: true  application:    name: item-writer
                 