/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.turkishairlines.concepts.shop.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Cart extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7669933304326508057L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Cart\",\"namespace\":\"com.turkishairlines.concepts.shop.models\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"cartItems\",\"type\":{\"type\":\"array\",\"items\":\"long\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Cart> ENCODER =
      new BinaryMessageEncoder<Cart>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Cart> DECODER =
      new BinaryMessageDecoder<Cart>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Cart> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Cart> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Cart> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Cart>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Cart to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Cart from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Cart instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Cart fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.util.List<java.lang.Long> cartItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cart() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param cartItems The new value for cartItems
   */
  public Cart(java.lang.Long id, java.util.List<java.lang.Long> cartItems) {
    this.id = id;
    this.cartItems = cartItems;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return cartItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: cartItems = (java.util.List<java.lang.Long>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'cartItems' field.
   * @return The value of the 'cartItems' field.
   */
  public java.util.List<java.lang.Long> getCartItems() {
    return cartItems;
  }


  /**
   * Sets the value of the 'cartItems' field.
   * @param value the value to set.
   */
  public void setCartItems(java.util.List<java.lang.Long> value) {
    this.cartItems = value;
  }

  /**
   * Creates a new Cart RecordBuilder.
   * @return A new Cart RecordBuilder
   */
  public static com.turkishairlines.concepts.shop.models.Cart.Builder newBuilder() {
    return new com.turkishairlines.concepts.shop.models.Cart.Builder();
  }

  /**
   * Creates a new Cart RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Cart RecordBuilder
   */
  public static com.turkishairlines.concepts.shop.models.Cart.Builder newBuilder(com.turkishairlines.concepts.shop.models.Cart.Builder other) {
    if (other == null) {
      return new com.turkishairlines.concepts.shop.models.Cart.Builder();
    } else {
      return new com.turkishairlines.concepts.shop.models.Cart.Builder(other);
    }
  }

  /**
   * Creates a new Cart RecordBuilder by copying an existing Cart instance.
   * @param other The existing instance to copy.
   * @return A new Cart RecordBuilder
   */
  public static com.turkishairlines.concepts.shop.models.Cart.Builder newBuilder(com.turkishairlines.concepts.shop.models.Cart other) {
    if (other == null) {
      return new com.turkishairlines.concepts.shop.models.Cart.Builder();
    } else {
      return new com.turkishairlines.concepts.shop.models.Cart.Builder(other);
    }
  }

  /**
   * RecordBuilder for Cart instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cart>
    implements org.apache.avro.data.RecordBuilder<Cart> {

    private long id;
    private java.util.List<java.lang.Long> cartItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.turkishairlines.concepts.shop.models.Cart.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cartItems)) {
        this.cartItems = data().deepCopy(fields()[1].schema(), other.cartItems);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Cart instance
     * @param other The existing instance to copy.
     */
    private Builder(com.turkishairlines.concepts.shop.models.Cart other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cartItems)) {
        this.cartItems = data().deepCopy(fields()[1].schema(), other.cartItems);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.turkishairlines.concepts.shop.models.Cart.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.turkishairlines.concepts.shop.models.Cart.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cartItems' field.
      * @return The value.
      */
    public java.util.List<java.lang.Long> getCartItems() {
      return cartItems;
    }


    /**
      * Sets the value of the 'cartItems' field.
      * @param value The value of 'cartItems'.
      * @return This builder.
      */
    public com.turkishairlines.concepts.shop.models.Cart.Builder setCartItems(java.util.List<java.lang.Long> value) {
      validate(fields()[1], value);
      this.cartItems = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cartItems' field has been set.
      * @return True if the 'cartItems' field has been set, false otherwise.
      */
    public boolean hasCartItems() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cartItems' field.
      * @return This builder.
      */
    public com.turkishairlines.concepts.shop.models.Cart.Builder clearCartItems() {
      cartItems = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Cart build() {
      try {
        Cart record = new Cart();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.cartItems = fieldSetFlags()[1] ? this.cartItems : (java.util.List<java.lang.Long>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Cart>
    WRITER$ = (org.apache.avro.io.DatumWriter<Cart>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Cart>
    READER$ = (org.apache.avro.io.DatumReader<Cart>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    long size0 = this.cartItems.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Long e0: this.cartItems) {
      actualSize0++;
      out.startItem();
      out.writeLong(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.Long> a0 = this.cartItems;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("cartItems").schema());
        this.cartItems = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readLong();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Long> a0 = this.cartItems;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("cartItems").schema());
            this.cartItems = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readLong();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










