/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.turkishairlines.concepts.shop.models;
@org.apache.avro.specific.AvroGenerated
public enum OrderState implements org.apache.avro.generic.GenericEnumSymbol<OrderState> {
  CREATED, VALIDATED, FAILED, SHIPPED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderState\",\"namespace\":\"com.turkishairlines.concepts.shop.models\",\"symbols\":[\"CREATED\",\"VALIDATED\",\"FAILED\",\"SHIPPED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
