debug: true
logging:
  #file:
    #name: app.log
  level:
    root: info
    org.apache.kafka: info
server: 
  port: 9005
spring:
  application:
    name: cart-processor
  cloud:
    stream:
      function:
        definition: processCart
      bindings:
        processCart-in-0:
          destination: cart
          consumer:
            use-native-decoding: true
        processCart-in-1:
          destination: itemsdb
          consumer:
            use-native-decoding: true
      kafka:
        streams:
          binder:
            functions:
              processCart:
                application-id: ${spring.application.name}-processCart
            applicationId: ${spring.application.name}-stream
            brokers:
            - localhost:19093
            - localhost:19094
            configuration:
              schema.registry.url: http://localhost:8081              
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
              processing.guarantee: exactly_once
              cart-materialized-as: cart-table
              item-materialized-as: cart-item-table
            autoCreateTopics: false
            autoAddPartitions: false
          bindings:
            processCart-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            processCart-in-0.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            processCart-in-1.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            processCart-in-1.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde