debug: true
logging:
  #file:    #name: app.log
  level:    root: info
    org.apache.kafka: info
custom:
  item:
    datasource:
      use: state-store
      url: jdbc:postgresql://localhost:5432/kafkaconnect
      username: dbuser
      password: db1234
      connection-timeout: 5000
      maximum-pool-size: 3
server: 
  port: 9002
spring:
  cloud:    stream:
      function:        definition: sinkItem, sendToDbTopic
      bindings:
        sinkItem-in-0:
          destination: items
          consumer:
            use-native-decoding: true
        sendToDbTopic-in-0:
          destination: items
          consumer:
            use-native-decoding: true
        sendToDbTopic-out-0:
          destination: itemsdb
          producer:
            use-native-encoding: true
      kafka:
        streams:
          binder:
            functions:
              sinkItem:
                application-id: ${spring.application.name}-sinkItem
              sendToDbTopic:
                application-id: ${spring.application.name}-sendToDbTopic
            applicationId: item-reader
            brokers:
            - localhost:19093
            - localhost:19094
            configuration:
              schema.registry.url: http://localhost:8081              
              default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
              processing.guarantee: exactly_once
              item-materialized-as: item-table              
            autoCreateTopics: false
            autoAddPartitions: false
          bindings:
            sinkItem-in-0.consumer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            sinkItem-in-0.consumer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde            sendToDbTopic-in-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            sendToDbTopic-in-0.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
            sendToDbTopic-out-0.producer.keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
            sendToDbTopic-out-0.producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
  application:    name: item-reader