debug: false
server:
  port: 9004
spring:
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
          autoAddPartitions: false
          brokers:
          - localhost:19093
          - localhost:19094   
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
      bindings:
        output:
          destination: cart
          content-type: application/*+avro
          producer:
            useNativeEncoding: true           
  application:
    name: cart-writer
