/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.corp.concepts.shop.models;
@org.apache.avro.specific.AvroGenerated
public enum Size implements org.apache.avro.generic.GenericEnumSymbol<Size> {
  XS, S, M, L, XL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Size\",\"namespace\":\"com.corp.concepts.shop.models\",\"symbols\":[\"XS\",\"S\",\"M\",\"L\",\"XL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
